spring:
  application:
    name: spring_eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}


---
server:
  port: 8762
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8763/eureka/

---
server:
  port: 8763
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8762/eureka/