spring:
  application:
    name: spring_eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}


---
server:
  port: 8762
spring:
  profiles: host8762
eureka:
  instance:
    hostname: 172.16.2.17
  client:
    service-url:
      defaultZone: http://172.16.2.17:8763/eureka/

---
server:
  port: 8763
spring:
  profiles: host8763
eureka:
  instance:
    hostname: 172.16.2.17
  client:
    service-url:
      defaultZone: http://172.16.2.17:8762/eureka/