server:
  port: 8761
#eureka:
#  client:
#    service-url:
#      defaulZone: hadoopslave4:8762/eureka/
#    register-with-eureka: false
#    fetch-registry: false

spring:
  application:
    name: spring_eureka_test


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://hadoopslave4:8762/eureka/
